language: node_js
node_js:
  - "9"
services:
  - mongodb
env:
  - PETAK_PORT=5000 PETAK_DATABASE_NAME=petak PETAK_HOST=127.0.0.1 PETAK_ENV=TEST
install:
  - npm install
before_script:
  - sleep 15
  - mongo petak_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test
